# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "nd"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2021 John S. Urban"
description = "compare numeric values in two otherwise similar files"

[dependencies]

[dependencies.M_CLI2]
   git = "https://github.com/urbanjost/M_CLI2.git"
[dependencies.M_framework]
   git = "https://github.com/urbanjost/M_framework.git"

[[executable]]
name = "nd"
source-dir = "app/"
main="nd.f90"
