# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "lsup"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2021 John S. Urban"
description = "list permissions of file and all parent directories "

[dependencies]

[dependencies.general_purpose_fortran]
   git = "https://github.com/urbanjost/general_purpose_fortran.git"
#[dependencies.M_io]
#   git = "https://github.com/urbanjost/M_io.git"
#[dependencies.M_system]
#   git = "https://github.com/urbanjost/M_system.git"

[[executable]]
name = "lsup"
source-dir = "app/"
main="lsup.f90"
