# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "lsup"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2021 John S. Urban"
description = "list permissions of file and all parent directories "

[dependencies]

[dependencies.GPF]
   git = "https://github.com/urbanjost/general-purpose-fortran.git"

[[executable]]
name = "lsup"
source-dir = "app/"
main="lsup.f90"
