name = "paranoia"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"

[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
[fortran]
# Fortran features
# Allows to toggle whether the default implicit typing should be used.  The default option is false.
implicit-typing = true  # default: false
# Allows to toggle whether external interfaces can be declared implicitly. The default option is false.
implicit-external = true  # default: false
