name = "colors"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2023, John S. Urban"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = false
[install]
   library = false
[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"

[dependencies]

   [dependencies.M_kracken]
      git = "https://github.com/urbanjost/M_kracken.git"
   [dependencies.M_color]
      git = "https://github.com/urbanjost/M_color.git"
