# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name        = "f90split"
version     = "0.1.0"
license     = "MIT"
author      = [ "M. Olagnon (Michel.Olagnon@ifremer.fr)", "Phil Garnatz, Cray Research Inc. ", "John S. Urban" ]
maintainer  = "urbanjost@comcast.net"
copyright   = "Copyright 2022, John S. Urban"
description = "split Fortran files"
categories  = ["Fortran"]
keywords    = ["fortran", "split"]
homepage    = "https://github.com/urbanjost/fpm-tools.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
   name="f90split"
   source-dir="app"
   main="f90split.f90"
   [executable.dependencies]
   M_CLI2         = { git = "https://github.com/urbanjost/M_CLI2.git" }
   M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
