setenv 'TRACE_FORMAT_SEARCH_PATH' '\\NTREL202.ntdev.corp.microsoft.com\4F18C3A5-CA09-4DBD-B6FC-219FDD4C6BE0\TraceFormat'
setenv 'HOMEPATH' '\Users\urbanjs'
setenv 'MANPATH' '/usr/local/man:/usr/share/man:/usr/man:/usr/local/man:/usr/share/man:/usr/man::/usr/ssl/man:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/doc/man:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/../man:/usr/ssl/man'
setenv 'APPDATA' 'C:\Users\urbanjs\AppData\Roaming'
setenv 'HOSTNAME' 'urbanjs-PC'
setenv 'PUBLISH_CMD' ''
setenv 'TERM' 'xterm'
setenv 'PROCESSOR_IDENTIFIER' 'x86 Family 15 Model 127 Stepping 2, AuthenticAMD'
setenv 'DFSTRACINGON' 'FALSE'
setenv 'LFILE' '/tmp/XWin.urbanjs.log'
setenv 'STARTPOINT' '/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA'
setenv 'WINDIR' 'C:\Windows'
setenv 'TEXDOCVIEW_txt' 'cygstart %s'
setenv 'TEXDOCVIEW_dvi' 'cygstart %s'
setenv 'WINDOWID' '8388643'
setenv 'PUBLIC' 'C:\Users\Public'
setenv 'OLDPWD' '/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/LIBRARY/STANDALONE'
setenv 'VDEVICE' 'X11'
setenv 'USERDOMAIN' 'urbanjs-PC'
setenv 'ALLUSERSPROFILE' 'C:\ProgramData'
setenv 'OS' 'Windows_NT'
setenv 'XTERM_SHELL' '/usr/bin/bash'
setenv 'USER' 'urbanjs'
setenv 'TEMP' '/cygdrive/c/Users/urbanjs/AppData/Local/Temp'
setenv 'COMMONPROGRAMFILES' 'C:\Program Files\Common Files'
setenv 'QTJAVA' 'C:\Program Files\QuickTime\QTSystem\QTJava.zip'
setenv 'USERNAME' 'urbanjs'
setenv 'TOP' '/cygdrive/d/backups/urbanjs.20100103'
setenv 'TEXDOCVIEW_pdf' 'cygstart %s'
setenv 'PROCESSOR_LEVEL' '15'
setenv 'PATH' '/usr/local/bin:/usr/bin:/bin:/cygdrive/d/backups/urbanjs.20100103/TWM/bin:/usr/local/bin:/usr/bin:/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Program Files/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files/QuickTime/QTSystem/:/usr/lib/lapack:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/..:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/scripts:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/scripts2:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_G95/:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_G95/TEST:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_G95/EXAMPLE:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_GFORTRAN/:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_GFORTRAN/TEST:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_GFORTRAN/EXAMPLE:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN/:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN/TEST:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN/EXAMPLE:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/scripts2/CYGWIN:/cygdrive/d/backups/urbanjs.20100103/TWM:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/../gfortran/bin:/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/../bin:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_X11:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_admin:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_cygwin:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_daily:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_dialog:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_examples:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_filter:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_html:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_lists:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_mail:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_missing:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_programming:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_screen:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_special:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_tests:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_vi:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_watch:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_www:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_xmore:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_xterm:/cygdrive/d/backups/urbanjs.20100103/TWM:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_X11:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_admin:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_cygwin:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_daily:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_dialog:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_examples:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_filter:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_html:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_lists:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_mail:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_missing:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_programming:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_screen:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_special:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_tests:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_vi:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_watch:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_www:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_xmore:/cygdrive/d/backups/urbanjs.20100103/TWM/scripts_xterm:/cygdrive/d/backups/urbanjs.20100103/TWM'
setenv 'SHIPTYPE' 'LONG'
setenv 'FP_NO_HOST_CHECK' 'NO'
setenv 'EXINIT' 'so /cygdrive/d/backups/urbanjs.20100103/TWM/scripts_vi/exrc'
setenv 'SYSTEMDRIVE' 'C:'
setenv 'PWD' '/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/LIBRARY/STANDALONE/CPRINTENV'
setenv 'EDITOR' 'vi'
setenv 'CYGWIN' '/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/..'
setenv 'USERPROFILE' 'C:\Users\urbanjs'
setenv 'TEXDOCVIEW_html' 'cygstart %s'
setenv 'LANG' 'C.UTF-8'
setenv 'NTIPath' 'C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static'
setenv 'QMAKESPEC' 'cygwin-g++'
setenv 'PS1' '\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
setenv 'LOGONSERVER' '\\URBANJS-PC'
setenv 'THOME' '/cygdrive/d/backups/urbanjs.20100103/TWM'
setenv 'PROCESSOR_ARCHITECTURE' 'x86'
setenv 'LOCALAPPDATA' 'C:\Users\urbanjs\AppData\Local'
setenv 'XTERM_LOCALE' 'C.UTF-8'
setenv 'XTERM_VERSION' 'Cygwin 6.8.99.903(255)'
setenv 'ProgramData' 'C:\ProgramData'
setenv 'HOME' '/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505'
setenv 'SHLVL' '4'
setenv 'PATHEXT' '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'
setenv 'HOMEDRIVE' 'C:'
setenv 'PROMPT' '$P$G'
setenv 'COMSPEC' 'C:\Windows\system32\cmd.exe'
setenv 'LOGNAME' 'urbanjs'
setenv 'TMP' '/cygdrive/c/Users/urbanjs/AppData/Local/Temp'
setenv 'SYSTEMROOT' 'C:\Windows'
setenv 'PROCESSOR_REVISION' '7f02'
setenv 'PRINTER' 'Send To OneNote 2007'
setenv 'CVS_RSH' '/bin/ssh'
setenv 'CLASSPATH' '.;C:\Program Files\QuickTime\QTSystem\QTJava.zip'
setenv 'TEXDOCVIEW_ps' 'cygstart %s'
setenv 'DISPLAY_TYPE' ''
setenv 'PROGRAMFILES' 'C:\Program Files'
setenv 'INFOPATH' '/usr/local/info:/usr/share/info:/usr/info:/usr/local/info:/usr/share/info:/usr/info:'
setenv 'DISPLAY' ':0.0'
setenv 'NUMBER_OF_PROCESSORS' '1'
setenv 'TWM' '/cygdrive/d/backups/urbanjs.20100103/TWM'
setenv 'SESSIONNAME' 'Console'
setenv 'XLOG' '/tmp/XLOG.0.urbanjs'
setenv 'COMPUTERNAME' 'URBANJS-PC'
setenv 'XAUTHORITY' '/cygdrive/d/backups/urbanjs.20100103/TWM/Xauthority'
setenv '_' '/cygdrive/d/backups/urbanjs.20100103/MYCYGWIN/DISKA/public_html/V505/bin/CYGWIN_G95/cprintenv'
