# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "minipre"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2023, John S. Urban"
description = "mini preprocessor"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"


[dependencies]
[dependencies.M_calculator]
   git = "https://github.com/urbanjost/M_calculator.git"
[dependencies.M_strings]
   git = "https://github.com/urbanjost/M_strings.git"

[[executable]]
name = "minipre"
source-dir = "app/"
main="main.f90"
