name = "FF08Depends"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2023, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
