# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "fcmd"
version = "0.1.0"
license = "MIT"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
author = "John S. Urban"
description= "General example programs"
categories = ["Fortran", "apps"]
keywords = ["fortran", "GPF", "General Purpose Fortran", "application", "example" ]
homepage = "https://github.com/urbanjost/apps.git"

executable = [
   { name="fcmd",    source-dir="app",  main="fcmd.f90"   },
#   { name="a2b",     source-dir="app",  main="a2b.f90"    },
#   { name="b2a",     source-dir="app",  main="b2a.f90"    },
#   { name="c2b",     source-dir="app",  main="c2b.f90"    },
#   { name="bz2az",   source-dir="app",  main="bz2az.f90"  },
#   { name="b2z",     source-dir="app",  main="b2z.f90"    },
#   { name="adsall",  source-dir="app",  main="adsall.f90" }
]

[build]
external-modules = ["ifport", "dfport"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
#M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }
M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
M_list         = { git = "https://github.com/urbanjost/M_list.git" }
M_system       = { git = "https://github.com/urbanjost/M_system.git" }
M_CLI2         = { git = "https://github.com/urbanjost/M_CLI2.git" }
M_kracken      = { git = "https://github.com/urbanjost/M_kracken.git" }
M_io           = { git = "https://github.com/urbanjost/M_io.git" }
