# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "sub"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2021 John S. Urban"
description = "change fixed strings in files"

[dependencies]

[dependencies.M_CLI2]
   git = "https://github.com/urbanjost/M_CLI2.git"
[dependencies.M_strings]
   git = "https://github.com/urbanjost/M_strings.git"
[dependencies.M_io]
   git = "https://github.com/urbanjost/M_io.git"
[dependencies.M_system]
   git = "https://github.com/urbanjost/M_system.git"
[dependencies.M_uuid]
   git = "https://github.com/urbanjost/M_uuid.git"

[[executable]]
name = "sub"
source-dir = "app/"
main="sub.f90"
