name = "redo"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2024, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]

[dependencies.M_history]
   git = "https://github.com/urbanjost/M_history.git"
[dependencies.M_calculator]
   git = "https://github.com/urbanjost/M_calculator.git"
[dependencies.M_framework]
   git = "https://github.com/urbanjost/M_framework.git"
[dependencies.M_io]
   git = "https://github.com/urbanjost/M_io.git"

#   [dependencies.M_kracken]
#      git = "https://github.com/urbanjost/M_kracken.git"
#   [dependencies.M_color]
#      git = "https://github.com/urbanjost/M_color.git"
# [dependencies.M_readline]
#    git = "https://github.com/urbanjost/M_readline.git"

[[executable]]
name = "redo"
source-dir = "app/"
main="redo.f90"
